---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/supernode version
      register: supernode_test_output
    - debug:
        msg: '{{ supernode_test_output.stdout }}'
    - command: /usr/local/bin/dfget version
      register: dfget_test_output
    - debug:
        msg: '{{ dfget_test_output.stdout }}'
    - command: /usr/local/bin/dfdaemon version
      register: dfdaemon_test_output
    - debug:
        msg: '{{ dfdaemon_test_output.stdout }}'
