---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ dragonfly_install_dir }}
  become: yes
  stat:
    path: '{{ dragonfly_install_dir }}'
  changed_when: False
  register: dragonfly_binary
- when: not dragonfly_binary.stat.exists
  block:
    - name: downloading {{ dragonfly_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ dragonfly_url }}'
        dest: '{{ dragonfly_tmp_tgz }}'
        checksum: '{{ dragonfly_checksum }}'
        mode: 0644
    - name: unarchiving {{ dragonfly_tmp_tgz }} to {{ dragonfly_parent_install_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ dragonfly_tmp_tgz }}'
        dest: '{{ dragonfly_parent_install_dir }}'
        creates: '{{ dragonfly_install_dir }}'
  always:
    - name: rm {{ dragonfly_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ dragonfly_tmp_tgz }}'
        state: absent
- name: linking items in {{ dragonfly_install_dir }} to items in {{ dragonfly_parent_install_dir }}/bin
  become: yes
  become_user: root
  with_items:
    - supernode
    - dfget
    - dfdaemon
  file:
    src: '{{ dragonfly_install_dir }}/{{ item }}'
    dest: '{{ dragonfly_parent_install_dir }}/bin/{{ item }}'
    state: link
